[package]
name = "aoc2024"
version = ["0.1.0"]
authors = ["Olivia Kaufman <olivia@olivia.wtf>"]
edition = "2021"

[dependencies]
reqwest = {version = "0.12.9", features = ["blocking"]}

[dev-dependencies]
httpmock = "0.7.0"
rand = "0.8.5"
tempfile = "3.14.0"

